import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RecoilContextProvider from './recoilContextProvider'
import Appbar from '@/components/Appbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <RecoilContextProvider>
        <body className={inter.className + " bg-gray-100"}> 
          {/* <InitUser /> */}
          <Appbar />
          {children}
        </body> 
      </RecoilContextProvider>
    </html>
  )
}



